// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Analyzes code and error messages to suggest corrections and explain the root cause of the error.
 *
 * - explainErrorContextually - A function that handles the code analysis and error explanation process.
 * - ExplainErrorContextuallyInput - The input type for the explainErrorContextually function.
 * - ExplainErrorContextuallyOutput - The return type for the explainErrorContextually function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainErrorContextuallyInputSchema = z.object({
  code: z
    .string()
    .describe('The code to analyze.'),
  errorMessage: z.string().describe('The error message associated with the code.'),
});
export type ExplainErrorContextuallyInput = z.infer<typeof ExplainErrorContextuallyInputSchema>;

const ExplainErrorContextuallyOutputSchema = z.object({
  correctedCode: z.string().describe('The corrected code with the error fixed.'),
  explanation: z.string().describe('The explanation of why the error occurred in the context of the code.'),
});
export type ExplainErrorContextuallyOutput = z.infer<typeof ExplainErrorContextuallyOutputSchema>;

export async function explainErrorContextually(input: ExplainErrorContextuallyInput): Promise<ExplainErrorContextuallyOutput> {
  return explainErrorContextuallyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainErrorContextuallyPrompt',
  input: {schema: ExplainErrorContextuallyInputSchema},
  output: {schema: ExplainErrorContextuallyOutputSchema},
  prompt: `You are an AI tool that analyzes code and error messages to suggest corrections and explain the root cause of the error.

Analyze the following code and error message, and provide the corrected code and an explanation of why the error occurred in the context of the code.

Code:
{{code}}

Error Message:
{{errorMessage}}

Corrected Code:
`, // Intentionally left blank; model will provide the code
  system: `You are an expert in debugging code and explaining errors. You will receive a piece of code and an error message. Your task is to provide the corrected code and explain why the error occurred in the context of the code. Be as specific as possible in your explanation, and provide the line number in the code where the error occurred.`
});

const explainErrorContextuallyFlow = ai.defineFlow(
  {
    name: 'explainErrorContextuallyFlow',
    inputSchema: ExplainErrorContextuallyInputSchema,
    outputSchema: ExplainErrorContextuallyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
