// This file is autogenerated by Firebase Studio.
// Do not edit this file manually.
//
// To update this file, run the following command:
//
//   npm run build
//
export {
  FileCode2,
  UploadCloud,
  Wand2,
  Play,
  Download,
  Loader2,
  FileText,
  File as FileIcon,
  X,
  Trash2,
  BookMarked,
  ClipboardPaste,
} from 'lucide-react';
